### ISSUE TITLE
Expressionify do not work on .NET 5.0

### ISSUE THREAD

**Issue by GoNextGroup** [ClaveConsulting/Expressionify#7] opened 2020-04-27 11:03 UTC
Since .NET 5.0 preview 1 Expressionify doesn't work because of missing IAsyncQueryProvider in Microsoft.EnitityFrameworkCore namespace.

**Comment by mariusGundersen** [comment] 2020-04-27 11:45
Interesting. Has it moved somewhere else or has there been larger changes to entity framework that makes it not work?

**Comment by GoNextGroup** [comment] 2020-04-28 23:59
I suppose it's connected with the massivelly changes. If I'm not mistaken, IAsyncQueryProvider was an internal class which was marked as "any time can be changes/removed" in the repo. So, the time's come.(((

**Comment by slangeder** [comment] 2020-07-09 07:39
@mariusGundersen I think that you can savely close this issue since the code in .NET 5.0 changed a lot since preview 1.
They moved the IAsyncQueryProvider back to the Microsoft.EntityFrameworkCore.Query namespace.
https://github.com/dotnet/efcore/blob/v5.0.0-preview.6.20312.4/src/EFCore/Query/IAsyncQueryProvider.cs

**Comment by mariusGundersen** [comment] 2020-07-09 10:50
I'm on holiday, so can't test it, have you confirmed if it works with .NET 5?

**Comment by slangeder** [comment] 2020-07-17 10:15
Nope, I didn't test it. But title of this issue made me nervous about using Expressionify in our project.
Since other EF Core extensions use `IAsyncQueryProvider` as well, I became even more nervous.

Anyway, what's the point of testing against a Preview version? I would not test it before NET 5 has a release candidate...

**Comment by snappyfoo** [comment] 2020-10-26 11:43
Well, EF Core 5.0 is on RC2 now and I get this error using Expressionify:

`System.TypeLoadException: 'Could not load type 'Microsoft.EntityFrameworkCore.Query.Internal.IAsyncQueryProvider' from assembly 'Microsoft.EntityFrameworkCore, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.'`

It's also my first time using Expressionify, so I can't rule out just using it incorrectly - could someone confirm?

**Comment by mariusGundersen** [comment] 2020-10-26 12:27
Yup, I tested it now and it seems to have just moved to `Microsoft.EntityFrameworkCore.Query`, which seems to indicate that this is now part of the official api and can be relied on. That's good news :+1:

**Comment by snappyfoo** [comment] 2020-10-26 12:35
Great! Would love to see a preview release with this fix if you’re able. Keep up the good work, thanks.

**Comment by mariusGundersen** [comment] 2020-10-26 16:46
I've published a version 5.0.0-beta.1 version now, it should show up in nuget in a few minutes.

This new version uses the Roslyn Source Generator, which is a lot less hacky than the msbuild code that it has used. There is one important breaking change, which will open up new functionality later:

**Classes that use [Expressionify] must now be marked as partial**

This way the generated expression can be placed on the same class and therefore use properties from the class or even instance. So I plan to remove the requirement that the method is `public static`, since that's not needed anymore.

**Comment by GoNextGroup** [comment] 2020-10-28 22:36
> I've published a version 5.0.0-beta.1 version now, it should show up in nuget in a few minutes.
> 
> This new version uses the Roslyn Source Generator, which is a lot less hacky than the msbuild code that it has used. There is one important breaking change, which will open up new functionality later:
> 
> **Classes that use [Expressionify] must now be marked as partial**
> 
> This way the generated expression can be placed on the same class and therefore use properties from the class or even instance. So I plan to remove the requirement that the method is `public static`, since that's not needed anymore.

Oh, cool, glad to see this, I'll try it soon and post results I'll give. Thank you!

**Comment by mariusGundersen** [comment] 2020-11-10 16:26
I made an attempt at getting it to work with non-static methods, but that was not as easy as I thought, so I will revert the changes and leave the .net 5 version working pretty much as the old version.

**Comment by mariusGundersen** [comment] 2021-02-22 05:34
Version 5 has now been released, which works with net 5.0

**Closed by mariusGundersen** 2021-02-22 05:34 UTC
